### ISSUE TITLE
Can't sync desktop dependencies

### ISSUE THREAD

**Issue by shub39** [Chaintech-Network/ComposeMultiplatformMediaPlayer#122]
Can't run a jvm desktop app because of gradle error

```bash
Execution failed for task ':composeApp:syncDesktopMainStartupLibs'.
> Could not resolve all files for configuration ':composeApp:desktopRuntimeClasspathComposeDev'.
   > Could not find org.jogamp.gluegen:gluegen-rt:2.5.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/jogamp/gluegen/gluegen-rt/2.5.0/gluegen-rt-2.5.0.pom
     Required by:
         project :composeApp > network.chaintech:compose-multiplatform-media-player:1.0.40 > network.chaintech:compose-multiplatform-media-player-jvm:1.0.40 > io.github.kevinnzou:compose-webview-multiplatform:1.9.40 > io.github.kevinnzou:compose-webview-multiplatform-desktop:1.9.40 > dev.datlag:kcef:2024.04.20.3 > dev.datlag:jcef:2024.04.20.3
   > Could not find org.jogamp.jogl:jogl-all:2.5.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/jogamp/jogl/jogl-all/2.5.0/jogl-all-2.5.0.pom
     Required by:
         project :composeApp > network.chaintech:compose-multiplatform-media-player:1.0.40 > network.chaintech:compose-multiplatform-media-player-jvm:1.0.40 > io.github.kevinnzou:compose-webview-multiplatform:1.9.40 > io.github.kevinnzou:compose-webview-multiplatform-desktop:1.9.40 > dev.datlag:kcef:2024.04.20.3 > dev.datlag:jcef:2024.04.20.3
```

looking into those dependencies, `gluegen-rt` and `jogl-all` only have upto `2.3.2`

**Comment by ctn-mobile-innovation** [comment]
@shub39 add Jogamp's Maven to your project's repositories:
 
repositories {
    maven("[https://jogamp.org/deployment/maven")](https://jogamp.org/deployment/maven%22))
}
 
 
For Example: https://github.com/Chaintech-Network/ComposeMultiplatformMediaPlayer/blob/main/settings.gradle.kts

**Comment by shub39** [comment]
Fixed. thanks!

**Comment by padmalcom** [comment]
The issue still exists in 1.0.52. Adding the maven repository still helps.
