### ISSUE TITLE
Local file playback not working on iOS

### ISSUE THREAD

**Issue by vfutia** [Chaintech-Network/ComposeMultiplatformMediaPlayer#43]
I have an MP4 file called "landing.mp4" that resides in "commonMain/composableResources/files".

I am using the following code to load this local resource.  It works as expected on Android, however on iOS the file does not load.

```
VideoPlayerComposable(
            modifier = Modifier.fillMaxSize(),
            playerConfig = PlayerConfig().apply {
                controlHideIntervalSeconds = 0 //hide immediately
            },
            url = Res.getUri("files/landing.mp4")
        )
```

**Comment by ctn-mobile-innovation** [comment]
To ensure local resources work on iOS, you need to add the files to the iOS bundle, as accessing local resources from "commanMain" won't work directly. This requires including the files separately in your iOS project.
For reference, we've implemented this approach in the demo project. Please explore the demo for a clearer understanding of how to handle local files effectively.

**Comment by vfutia** [comment]
@ctn-mobile-innovation much appreciated!  I took a look through the example but I must have missed that.  It's still not working with the original video but I'm wondering if it has to do with the encoding.  I can get other mp4 videos to work on iOS and Android.  Thank you!!
